import Head from 'next/head'
import { Character as CharacterType } from '@/typescript/types'
import Characters from '@/components/characters';

type Props = {
  characters: CharacterType[];
}

export default function Home({ characters }: Props) {
  return (
    <>
      <Head>
        <title>Star wars characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Star wars users</h1>
        {<Characters characters={characters} />}  
      </main>
    </>
  )
}

export async function getStaticProps() {
  const request = await fetch('https://swapi.dev/api/people');
  const characters = await request.json();

  return {
    props: {
        characters: characters.results,
    }
  }
}